export const NON_POURING_WORK_OPTIONS = [
  'Clean Pump',
  'Climb Boom',
  'Deliveries',
  'Dismantle Boom',
  'Dismantle Other',
  'Dismantle Pump',
  'Housekeeping',
  'Inspections',
  'Install Crucifix/Base',
  'Install HD Bolts',
  'Installation Boom',
  'Installation Other',
  'Installation Pump',
  'Maintenance',
  'Pipe Testing',
  'Pipeline Installation',
  'Pipeline Relocation',
  'Preparation to Climb Boom',
  'Transfer Line Relocation',
  'Other',
];
